server:
  port: ${APP_PORT:8082}

token:
  secret:
    key: ${TOKEN_SECRETKEY}
  expiration:
    time: ${TOKEN_EXPIRATION}

spring:
  data:
    mongodb:
      database: ${DB_NAME:carcare}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      host: ${DB_HOST:localhost}
      port: ${DB_PORT}

